### ISSUE TITLE
NCPA 3 - Windows -- logs endpoint broken when passive running

### ISSUE THREAD

**Issue by ne-bbahn** [NagiosEnterprises/ncpa#1075]
>               I have the same problem. Here is example of config and what the ncpa_passive.log says.
> ![image](https://github.com/NagiosEnterprises/ncpa/assets/38576265/c86e40c2-1ea6-485d-bee5-3ecb54973459)
> ![image](https://github.com/NagiosEnterprises/ncpa/assets/38576265/6b223e74-0174-470c-8274-d57e81d8ef30)
> 
> _Originally posted by @rob2791 in https://github.com/NagiosEnterprises/ncpa/issues/1030#issuecomment-1836293795_
>             

It seems the `logs` API endpoint (only on windows) doesn't work when you pass parameters to it (these are necessary for it to work in the first place). 

I have verified that the endpoint (with parameters) is accessible in the interface, but not via URL/request.

**Comment by ne-bbahn** [comment]
It seems that the `logs` endpoint DOES work if `System` in `?name=System` is capitalized as listed here. I'll see if I can fix this to work as it did with NCPA 2 to ignore case

**Comment by ne-bbahn** [comment]
I believe this should be solved in NCPA 3.0.2, but will need to investigate.

**Comment by uGeeko** [comment]
I had this same issue. As i was using PowerShell .ps1 scripts, we had to change the ncpa.cfg to use 64 bit powershell and not 32-bit version.

**Comment by ne-bbahn** [comment]
> I had this same issue. As i was using PowerShell .ps1 scripts, we had to change the ncpa.cfg to use 64 bit powershell and not 32-bit version.

Have you tested to see if the issue persists with NCPA 3.0.2?

**Comment by uGeeko** [comment]
This was still happening for us on version 3.0.2. 64-bit NCPA can not process the following to launch Powershell. It does not understand "sysnative" part of the command.
.ps1 = c:\windows\sysnative\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -File $plugin_name $plugin_args

We switched to using the below to launch Powershell in 64-bit
.ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args

**Comment by ne-bbahn** [comment]
It seems you had modified your configuration as 
`.ps1 = powershell -ExecutionPolicy Bypass -File $plugin_name $plugin_args` 
is the default configuration.

Since this seems to be a configuration issue that was resolved by returning to the default configuration and I can't reproduce it, I will close this issue.
