### ISSUE TITLE
Plugin arguments doesnt work with check_http_json.py

### ISSUE THREAD

**Issue by ccztux** [NagiosEnterprises/ncpa#937]
I have issues with the plugin arguments used by `check_http_json.py`.

Neither this call:

```
[root@tux01 ~]# ./check_ncpa.py -H 10.0.0.10 -t mytoken -M plugins/check_http_json.py -a '-H inside01 -P 443 -p interface-rest/incident/count?incidentType=failedTask -s -w count,@1: -c count,@1: -e count' -v
Connecting to: https://10.0.0.10:5693/api/plugins/check_http_json.py/-H/inside01/-P/443/-p/interface-rest%2Fincident%2Fcount%3FincidentType%3DfailedTask/-s/-w/count%2C%401%3A/-c/count%2C%401%3A/-e/count?token=mytoken&check=1
File returned contained:
{
    "returncode": 2,
    "stdout": "usage: check_http_json.py [-h] [-d] [-s] -H HOST [-k] [-V] [--cacert CACERT]\n                          [--cert CERT] [--key KEY] [-P PORT] [-p PATH]\n                          [-t TIMEOUT] [-B AUTH] [-D DATA] [-A HEADERS]\n                          [-f SEPARATOR] [-F VALUE_SEPARATOR]\n                          [-w [KEY_THRESHOLD_WARNING [KEY_THRESHOLD_WARNING ...]]]\n                          [-c [KEY_THRESHOLD_CRITICAL [KEY_THRESHOLD_CRITICAL ...]]]\n                          [-e [KEY_LIST [KEY_LIST ...]]]\n                          [-E [KEY_LIST_CRITICAL [KEY_LIST_CRITICAL ...]]]\n                          [-q [KEY_VALUE_LIST [KEY_VALUE_LIST ...]]]\n                          [-Q [KEY_VALUE_LIST_CRITICAL [KEY_VALUE_LIST_CRITICAL ...]]]\n                          [-u [KEY_VALUE_LIST_UNKNOWN [KEY_VALUE_LIST_UNKNOWN ...]]]\n                          [-y [KEY_VALUE_LIST_NOT [KEY_VALUE_LIST_NOT ...]]]\n                          [-Y [KEY_VALUE_LIST_NOT_CRITICAL [KEY_VALUE_LIST_NOT_CRITICAL ...]]]\n                          [-m [METRIC_LIST [METRIC_LIST ...]]]\ncheck_http_json.py: error: unrecognized arguments: incident count?incidentType=failedTask"
}
usage: check_http_json.py [-h] [-d] [-s] -H HOST [-k] [-V] [--cacert CACERT]
                          [--cert CERT] [--key KEY] [-P PORT] [-p PATH]
                          [-t TIMEOUT] [-B AUTH] [-D DATA] [-A HEADERS]
                          [-f SEPARATOR] [-F VALUE_SEPARATOR]
                          [-w [KEY_THRESHOLD_WARNING [KEY_THRESHOLD_WARNING ...]]]
                          [-c [KEY_THRESHOLD_CRITICAL [KEY_THRESHOLD_CRITICAL ...]]]
                          [-e [KEY_LIST [KEY_LIST ...]]]
                          [-E [KEY_LIST_CRITICAL [KEY_LIST_CRITICAL ...]]]
                          [-q [KEY_VALUE_LIST [KEY_VALUE_LIST ...]]]
                          [-Q [KEY_VALUE_LIST_CRITICAL [KEY_VALUE_LIST_CRITICAL ...]]]
                          [-u [KEY_VALUE_LIST_UNKNOWN [KEY_VALUE_LIST_UNKNOWN ...]]]
                          [-y [KEY_VALUE_LIST_NOT [KEY_VALUE_LIST_NOT ...]]]
                          [-Y [KEY_VALUE_LIST_NOT_CRITICAL [KEY_VALUE_LIST_NOT_CRITICAL ...]]]
                          [-m [METRIC_LIST [METRIC_LIST ...]]]
check_http_json.py: error: unrecognized arguments: incident count?incidentType=failedTask
```

nor that:

```
[root@tux01 ~]# ./check_ncpa.py -H 10.0.0.10 -t mytoken -M plugins/check_http_json.py -q args='-H inside01 -P 443 -p interface-rest/incident/count?incidentType=failedTask -s -w count,@1: -c count,@1: -e count' -v
An error occurred:
need more than 1 value to unpack
```

works.

I have fixed this for me and will provide the fix via a pull request. The fix adds the following new argument to `check_ncpa.py`:

```
  -r RAW_PLUGIN_ARGS, --raw-plugin-args=RAW_PLUGIN_ARGS
                        Raw plugin arguments for the plugin to be run. This is
                        an alternative to -a and should be used if the
                        arguments are more complex, like URL parameters.
                        Example: -r '-H inside01 -P 443 -p interface-
                        rest/incident/count?incidentType=failedTask -s -w
                        count,@1: -c count,@1: -e count'
```

**Comment by JamieSimon2** [comment]
Please merge @ccztux 's commit, it fixes my problem with `check_ncpa.py` for the `check_http` (and similar) plugins.

**Comment by ccztux** [comment]
@JamieSimon2 Do you have any issues using the `-a` argument? There was an issue using it, but this should be fixed.

**Comment by JamieSimon2** [comment]
Yes, the current release at https://github.com/NagiosEnterprises/ncpa/blob/master/client/check_ncpa.py has the exact problem described above. Arguments with slashes and other characters aren't interpreted/parsed correctly and result in bad NCPA responses.

**Comment by ccztux** [comment]
The changes were merged into the `maint` branch.
[Try the version from the maint branch.](https://github.com/NagiosEnterprises/ncpa/blob/maint/client/check_ncpa.py)

**Comment by JamieSimon2** [comment]
I regret to report my testing of https://github.com/NagiosEnterprises/ncpa/blob/maint/client/check_ncpa.py indicates "-a" still does not work correctly with the "/" character, but the "-r" argument does.
```
[centos@lab-eu-1b-1209-h17 ~]$ /usr/bin/python3 /usr/lib64/nagios/plugins/check_ncpa.py -H 172.19.6.0 -P 5693 -t "MYTOKEN" -M "plugins/check_http" -r "-I 172.19.6.0 -p 3000 -u /login --onredirect=follow"
HTTP OK: HTTP/1.0 200 OK - 32253 bytes in 0.006 second response time |time=0.005890s;;;0.000000 size=32253B;;;0
[centos@lab-eu-1b-1209-h17 ~]$ /usr/bin/python3 /usr/lib64/nagios/plugins/check_ncpa.py -H 172.19.6.0 -P 5693 -t "MYTOKEN" -M "plugins/check_http" -a "-I 172.19.6.0 -p 3000 -u /login --onredirect=follow"
HTTP WARNING: HTTP/1.1 400 Bad Request - 103 bytes in 0.000 second response time |time=0.000440s;;;0.000000 size=103B;;;0
```
